Document: crystal-facet-uml
Title: Debian crystal-facet-uml Manual
Author: <insert document author here>
Abstract: This manual describes what crystal-facet-uml is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/crystal-facet-uml/crystal-facet-uml.sgml.gz

Format: postscript
Files: /usr/share/doc/crystal-facet-uml/crystal-facet-uml.ps.gz

Format: text
Files: /usr/share/doc/crystal-facet-uml/crystal-facet-uml.text.gz

Format: HTML
Index: /usr/share/doc/crystal-facet-uml/html/index.html
Files: /usr/share/doc/crystal-facet-uml/html/*.html
